# Generated by Django 5.2.11 on 2026-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome class (e.g., "fab fa-react", "fab fa-python")', max_length=100, null=True),
        ),
    ]
